[package]
name = "orx-concurrent-vec"
version = "1.6.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient, convenient and lightweight grow-only read & write concurrent data structure allowing high performance concurrent collection."
license = "MIT"
repository = "https://github.com/orxfun/orx-concurrent-vec/"
keywords = ["concurrency", "vec", "data-structures", "atomic", "lock-free"]
categories = ["data-structures", "concurrency", "rust-patterns"]

[dependencies]
orx-concurrent-bag = "1.12"
orx-fixed-vec = "2.8"
orx-pinned-concurrent-col = "1.1"
orx-pinned-vec = "2.8"
orx-split-vec = "2.9"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rayon = "1.9.0"
test-case = "3.3.1"

[[bench]]
name = "collect_with_push"
harness = false
