[package]
name = "orx-concurrent-vec"
version = "3.0.1"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "A thread-safe, efficient and lock-free vector allowing concurrent grow, read and update operations."
license = "MIT"
repository = "https://github.com/orxfun/orx-concurrent-vec/"
keywords = ["concurrency", "vec", "data-structures", "atomic", "lock-free"]
categories = ["data-structures", "concurrency", "rust-patterns", "no-std"]

[dependencies]
orx-pseudo-default = { version = "1.4", default-features = false }
orx-pinned-vec = "3.10"
orx-fixed-vec = "3.10"
orx-split-vec = "3.10"
orx-pinned-concurrent-col = "2.8"
orx-concurrent-option = "1.3"

[dev-dependencies]
clap = { version = "4.5.17", features = ["derive"] }
criterion = "0.5.1"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1.9.0"
test-case = "3.3.1"
append-only-vec = "0.1.5"
boxcar = "0.2.5"

[[bench]]
name = "collect_with_extend"
harness = false
