[package]
name = "orx-concurrent-vec"
version = "2.5.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient, convenient and lightweight grow-only read & write concurrent data structure allowing high performance concurrent collection."
license = "MIT"
repository = "https://github.com/orxfun/orx-concurrent-vec/"
keywords = ["concurrency", "vec", "data-structures", "atomic", "lock-free"]
categories = ["data-structures", "concurrency", "rust-patterns"]

[dependencies]
orx-pseudo-default = "1.4"
orx-pinned-vec = "3.4"
orx-fixed-vec = "3.4"
orx-split-vec = "3.4"
orx-pinned-concurrent-col = "2.4"
orx-concurrent-option = "1.1"

[dev-dependencies]
orx-concurrent-bag = "2.4"
criterion = "0.5.1"
rand = "0.8.5"
rayon = "1.9.0"
test-case = "3.3.1"
append-only-vec = "0.1.5"

[[bench]]
name = "collect_with_extend"
harness = false
